apiVersion: v1
kind: Service
metadata:
  name: verdaccio
  labels:
    app: verdaccio
spec:
  type: LoadBalancer
  ports:
  - port: 4873
    targetPort: 4873
    protocol: TCP
  selector:
    app: verdaccio
